// <auto-generated />
using System;
using DevClinic.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevClinic.Data.Migrations
{
    [DbContext(typeof(DevClinic_Context))]
    [Migration("20230531040556_UpdatedAt_Register")]
    partial class UpdatedAt_Register
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DevClinic.Domain.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Phone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Plan");

                    b.Property<string>("Register")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Register");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Sexo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tb_Clients", (string)null);
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("Phone");

                    b.Property<string>("Register")
                        .IsRequired()
                        .HasColumnType("varchar(6)")
                        .HasColumnName("Register");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("varchar(1)")
                        .HasColumnName("Sexo");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tb_Doctor", (string)null);
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Doctor_Speciality", b =>
                {
                    b.Property<int>("SpecilityId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.HasKey("SpecilityId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("tb_Doctor_Specility", (string)null);
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Speciality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NameSpeciality")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Speciality");

                    b.HasKey("Id");

                    b.ToTable("tb_Speciality", (string)null);
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Doctor_Speciality", b =>
                {
                    b.HasOne("DevClinic.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Specialities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevClinic.Domain.Entities.Speciality", "Speciality")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Speciality");
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Specialities");
                });

            modelBuilder.Entity("DevClinic.Domain.Entities.Speciality", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
